changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Product changes
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation and maintenance
      labels:
        - documentation
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - "*"
